Description: |
  aws-logs-converter-s3-access
  SAM template for running the aws-logs-converter for S3 Access Logs on EMR
Parameters:
  EmrScriptBucketUri:
    Type: String
    Description: S3 URI to EMR job script
  ApplicationId:
    Type: String
    Description: Application ID of EMR Serverless to run job
  MyJobExecutionRoleARN:
    Type: String
    Description: IAM EMR Serverless execution role ARN
  S3LogBucket:
    Type: String
    Description: Name of the S3 bucket containing the S3 access logs
  JobName:
    Type: String
    Description: Name of the state machine and emr job
    Default: aws-logs-converter-s3-access
  JonCronSchedule:
    Type: String
    Description: Schedule of job in CRON format
    Default: '10 0 * * ? *'
AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Resources:
  EmrServerlessStateMachine:
    Type: AWS::Serverless::StateMachine
    Properties:
      Name: !Ref JobName
      DefinitionUri: statemachine.asl.json
      DefinitionSubstitutions:
        EmrScriptBucketUri: !Ref EmrScriptBucketUri
        ApplicationId: !Ref ApplicationId
        MyJobExecutionRoleARN: !Ref MyJobExecutionRoleARN
        S3LogBucket: !Ref S3LogBucket
        JobName: !Ref JobName
      Role:
        Fn::GetAtt:
          - EmrServerlessStateMachineRole
          - Arn
  EmrServerlessStateMachineRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: states.amazonaws.com
            Action: 'sts:AssumeRole'
      Policies:
        - PolicyName: EmrServerlessPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - 'emr-serverless:StartJobRun'
                  - 'emr-serverless:GetJobRun'
                  - 'iam:PassRole'
                Resource: '*'
  EventBridgeInvokeStepFunctionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: events.amazonaws.com
            Action: 'sts:AssumeRole'
      Policies:
        - PolicyName: InvokeStepFunctionPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action: 'states:StartExecution'
                Resource:
                  - !GetAtt EmrServerlessStateMachine.Arn
  EmrServerlessSchedule:
    Type: AWS::Events::Rule
    Properties:
      Description: !Ref JobName
      Name: !Ref JobName
      ScheduleExpression:
        Fn::Sub: 'cron(${JonCronSchedule})'
      State: 'ENABLED'
      Targets:
        - Arn:
            Fn::Sub: arn:aws:states:${AWS::Region}:${AWS::AccountId}:stateMachine:${JobName}
          Id: 'EmrServerlessStateMachineTarget'
          RoleArn:
            Fn::GetAtt:
              - EventBridgeInvokeStepFunctionRole
              - Arn
    DependsOn: EmrServerlessStateMachine

Outputs:
  EmrServerlessStateMachineArn:
    Description: 'ARN of the State Machine'
    Value:
      Ref: EmrServerlessStateMachine